### ISSUE TITLE
Support ValueTask<T> usage from NetStandard assemblies for Xamarin.Android

### ISSUE THREAD

**Issue by jonathanpeppers** [mono/mono#10142]
We have a few reports of this issue, such as:
- `System.Reactive`: https://github.com/dotnet/reactive/issues/803#issuecomment-413344838
- `Xamarin.Android`: https://github.com/xamarin/xamarin-android/issues/1879

This is fixed in https://github.com/mono/mono/pull/9968, but it is only available in `2018-06`.

Since Visual Studio 15.8 shipped to stable _yesterday_, perhaps we need to look into getting this into a service release for 15.8? We are using `2018-02` on 15.8 at the moment.

From @brendanzagaeski:

> As it stands, it looks like the .NET Core folks assumed `ValueTask<T>` (and the other types from System.Threading.Tasks.Extensions) were public in Mono, and they added placeholder files for Xamarin project types in the NuGet package.

## Steps to Reproduce

1. File | New Xamarin.Android project
1. Reference a netstandard library that has a dependency on the `System.Threading.Tasks.Extensions` NuGet package
2. Build fails

### Current Behavior

Xamarin.Android builds fail when using `System.Reactive` or netstandard libraries that have a dependency on `System.Threading.Tasks.Extensions`.

### Expected Behavior

Xamarin.Android supports this scenario.

**Comment by brendanzagaeski** [comment]
Small correction to my comment: I should have said "saw" rather than "assumed" in "the .NET Core folks _saw_ that `ValueTask<T>` (and the other types from System.Threading.Tasks.Extensions) were public in Mono..." Those types do all exist and are all public in the current Xamarin SDKs.

I double-checked this quickly with `monop`. All the property and method names from lib/netstandard2.0/System.Threading.Tasks.Extensions.xml (from the NuGet package) are included in mscorlib.dll on Xamarin.Android and Xamarin.iOS. I also checked quickly with `monodis` to see if any of the methods throw exceptions like `NotImplementedException`. It looks like none of them do. So at least based on that quick double-check, it seems that the only missing thing for these types in  `mono/2018-02` is indeed the facade assembly.

**Comment by onovotny** [comment]
Bump?

**Comment by marek-safar** [comment]
This is indeed a duplicate of #9968.

@brendanzagaeski could you figure out if that meets the bar for SR and if there is one planned.

**Comment by brendanzagaeski** [comment]
Apologies for the slow follow-up on my side. I'm not too familiar with whether parity among different .NET target frameworks is generally accepted as a reason for inclusion of a change in a Visual Studio servicing release. Deciding the policy for that sounds like a higher-level discussion that'd be above me. (Depending on how .NET Core expects to add other new features in the future, this example situation might also be good to include in a more general discussion about how Mono and .NET Core will plan to coordinate on timing of API parity moving forward.)

**Comment by jonathanpeppers** [comment]
Xamarin.Android in VS 15.9 should have this fix, since it was backported to mono 2018-04: 
* 15.9 submodules -https://github.com/xamarin/xamarin-android/tree/d15-9/external
* Mono at: https://github.com/mono/mono/commits/000780ca82c87316227f1da94314587022d02f70
* I see the commit: https://github.com/mono/mono/commit/9fca0d8760e4ad561e95d1d96b27a2c808734ead

@ahmedalejo is the problem fixed for you in Xamarin.Android 9.1.0.38?

**Comment by brendanzagaeski** [comment]
>  is the problem fixed for you in Xamarin.Android 9.1.0.38?

Note that the System.Threading.Tasks.Extensions.dll facade assembly is missing from Xamarin.Android version 9.1.0.38, so this issue won't quite be resolved there. That said, now that https://github.com/xamarin/xamarin-android/commit/0ea0725c2e9ca86b665ed49dfef0e0146251f7f9 has been committed, it is likely appropriate to backport the part of https://github.com/xamarin/xamarin-android/pull/2450 that adds the facade assembly to the Xamarin.Android installer package. I will create an issue against xamarin-android to suggest and track that.

**Comment by brendanzagaeski** [comment]
Follow-up item about the missing facade assembly filed: https://github.com/xamarin/xamarin-ndroid/issues/2466

**Comment by marek-safar** [comment]
The issue has been resolved on Mono side, even 2018-04 now exposes complete System.Threading.Task.Extensions

**Comment by nexxuno** [comment]
Hello, I know some time has passed, but this problem seems to be still present on VS2019 azure build machines. Is it possible after all this time?

**Comment by jonathanpeppers** [comment]
@nexxuno can you file a new issue with a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!

https://github.com/xamarin/xamarin-android/issues

**Comment by nexxuno** [comment]
I was able to build correctly, now I have another unrelated problem and I opened antoher issue. Thanks.
