### ISSUE TITLE
Showstopper: Mono 5.20.1.19 breaks HttpListener with https

### ISSUE THREAD

**Issue by MartinRothschink** [mono/mono#14721]
Application with REST-API in OWIN self hosted environment (based on HttpListener) fails to communicate over https (http is still working). This was already working in Mono 5.16/5.18.

## Steps to Reproduce

1. Register a certificate for port 7783 (done in Mono 5.18, see https://github.com/mono/mono/issues/14152)

2. Run sample program below

3. Access from browser with http://hostname:7782 returns `Hello world 5/31/2019 9:43:07 AM`

4. Access from browser with https://hostname:7783 returns `ERR_CONNECTION_CLOSED`

## Sample code

```
     static void Main(string[] args)
      {
         HttpListener listener = new HttpListener();
         listener.Prefixes.Add("http://*:7782/");
         listener.Prefixes.Add("https://+:7783/");
         listener.Start();

         while (true)
         {
            try
            {
               var request = listener.GetContext();
               var response = request.Response;

               var responseString = $"<html><body>Hello world {DateTime.Now}</body></html>";
               var buffer = System.Text.Encoding.UTF8.GetBytes(responseString);

               response.ContentLength64 = buffer.Length;
               response.OutputStream.Write(buffer, 0, buffer.Length);
               response.OutputStream.Close();
            }
            catch (Exception e)
            {
               Console.WriteLine(e);
            }
         }
      }
```

### Current Behavior

https does not work and closes connection

### Expected Behavior

http and https should both return same data

## On which platforms did you notice this

[ ] macOS
[x] Linux, all distros
[ ] Windows

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

## Stacktrace

The sample code does **not** throw any exception.

Running mono --trace shows these exceptions in the trace:

```
[0x7faed4390740:] EXCEPTION handling: System.Net.Sockets.SocketException: Could not resolve host '+'
EXCEPTION: catch found at clause 0 of System.Net.EndPointManager:GetEPListener (string,int,System.Net.HttpListener,bool)

[0x7faed4390740:] EXCEPTION handling: System.Security.Cryptography.CryptographicException: `MonoBtlsPkcs12.Import` failed.
EXCEPTION: finally clause 3 of Mono.Btls.X509CertificateImplBtls:ImportPkcs12 (byte[],Microsoft.Win32.SafeHandles.SafePasswordHandle)

EXCEPTION: catch found at clause 3 of Mono.Btls.X509CertificateImplBtls:Import (byte[],Microsoft.Win32.SafeHandles.SafePasswordHandle,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)

[0x7faed4390740:] EXCEPTION handling: System.PlatformNotSupportedException: Operation is not supported on this platform.
EXCEPTION: catch found at clause 0 of System.Net.HttpListener:LoadCertificateAndKey (System.Net.IPAddress,int)
```

## Note

The last exception is probably the same as in issue https://github.com/mono/mono/issues/14152

Happens also in Mono 6.0.0.0.273!

**Comment by steveisok** [comment]
@MaximLipnin can you please take a look at this?

**Comment by baulig** [comment]
Should be fixed with https://github.com/mono/mono/pull/14860.

**Comment by baulig** [comment]
Fixed in #14860.

**Comment by MartinRothschink** [comment]
Any plan to release a 5.20+ update?

**Comment by squirrl** [comment]
I still see this issue under Mono 6.0.0.319, using the provided example project, as well as my project which is known to work under .Net 4.7.2.

**Comment by steveisok** [comment]
@baulig - Please take a look

**Comment by baulig** [comment]
We current do not support `+` (or any IPv6 addresses), using

```
         listener.Prefixes.Add("https://*:7783/");
```

You also mentioned that you got this on Linux - did you build your Mono yourself or use some package?

The only way you can possibly get a `PlatformNotSupportedException` there is if something got very badly messed up during the build process:

https://github.com/mono/mono/blob/4780486237dfc9feab14317239593b90cd5b3d18/mcs/class/System/System.Net/HttpListener.Mono.cs#L93

**Comment by squirrl** [comment]
I have this problem whether using 

    listener.Prefixes.Add("https://+:7783/");
or

    listener.Prefixes.Add("https://*:7783/");

This is using the Mono 6.0.0.319 directly from the https://download.mono-project.com/repo/ubuntu stable-bionic repository. I have also seen this issue on Centos 7.

**Comment by MartinRothschink** [comment]
@baulig Are you sure? I have used the + binding for https successfully on Mono 5.x. How do I tell Mono to use https if that is not supported?

**Comment by baulig** [comment]
We do not support the `+` syntax - this will always throw, but the exception is caught and it'll fallback to `*`.  This is the first exception that you saw.

The second exception is to be expected as well, it's completely normal and to be expected.

The third exception happens when you're using an unsupported certificate or key.  Which you were because a certification without any private key is of cause not acceptable - and since you are using BTLS, _all_ certificates were always loaded without private key due to this bug: https://github.com/mono/mono/issues/16189.  There's already a PR up for this which should land shortly: https://github.com/mono/mono/pull/16212.

Could you please try again after we've landed #16212 to see whether that fixed your problem?

**Comment by baulig** [comment]
Should have been fixed with #16212.  If you're still having this issue, then please reopen.

**Comment by squirrl** [comment]
I'm still seeing ERR_CONNECTION_RESET using the example program (and my production program) under Mono 6.0.0.327

**Comment by steveisok** [comment]
@squirrl Looks like the fix wasn't backported to where it needed to be.  My apologies.

**Comment by Martidjen** [comment]
> 
> 
> I'm still seeing ERR_CONNECTION_RESET using the example program (and my production program) under Mono 6.0.0.327

Just want to drop in and say i'm seeing the same error when trying to communicate over https, have not been able to use https since mono version 5.20.1.19. 
Hope #16212 will fix this, any idea when this will be released again?
Thank you for your support

**Comment by steveisok** [comment]
As of right now, I'm unsure what version will contain https://github.com/mono/mono/pull/16212.  When I know, I'll update the ticket.

**Comment by Martidjen** [comment]
Updated mono to version 3.0.0.334, deleted and added certs through httpcfg again, but still no https. Was I trying too soon??

**Comment by squirrl** [comment]
This is still a major showstopper for my team on version 6.4.0.198.

If there is some logging output I can provide, I'm happy to, just let me know where to look.

**Comment by Martidjen** [comment]
Same for me, would be glad to help as well. 

Please let us know :)

**Comment by steveisok** [comment]
From the looks of it, the fix hasn't made it to preview yet.  It'll be in the version bundled w/ d16-4 release, which I think is coming relatively soon to preview.

**Comment by Martidjen** [comment]
Any news on an update yet?

**Comment by Martidjen** [comment]
Will this be fixed in mono version 6.6.0 and will this version be released any time soon?
Looks like 6.6.0 is already used in Visual Studio 2019 version 16.4 with Xamarin.Android 10.1.0.30 which was released yesterday?

**Comment by Martidjen** [comment]
Happy to say that the issue is fixed with version 6.6.0.161
Thank you for your support
