### ISSUE TITLE
[netcore] Make System.Text.Json.Serialization.Tests.ValueTests.ValueFail Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15154]
The test currently fails with:

```
System.Text.Json.Serialization.Tests.ValueTests.ValueFail [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.MemberAccessException): Cannot create an abstract class: System.Enum
      ---- System.MemberAccessException : Cannot create an abstract class: System.Enum
      Stack Trace:
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
           at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
           at System.Text.Json.Serialization.ReflectionEmitMaterializer.CreateConstructor(Type type)
           at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
           at System.Text.Json.Serialization.ReadStackFrame.Initialize(Type type, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
           at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializer.Parse[Enum](String json, JsonSerializerOptions options)
           at System.Text.Json.Serialization.Tests.ValueTests.<>c__DisplayClass9_0.<ValueFail>b__29()
        ----- Inner Stack Trace -----
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
           at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
           at System.Text.Json.Serialization.ReflectionEmitMaterializer.CreateConstructor(Type type)
           at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
           at System.Text.Json.Serialization.ReadStackFrame.Initialize(Type type, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
           at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
           at System.Text.Json.Serialization.JsonSerializer.Parse[Enum](String json, JsonSerializerOptions options)
           at System.Text.Json.Serialization.Tests.ValueTests.<>c__DisplayClass9_0.<ValueFail>b__29()
```

It appears that JsonSerializer.Parse<Enum>(...) generates invalid IL through DynamicMethod,
Mono throws "System.MemberAccessException: Cannot create an abstract class: System.Enum" from System.Reflection.Emit.DynamicMethod.CreateDelegate
, CoreCLR creates the delegate, but fails to execute it with "System.InvalidOperationException: Instances of abstract classes cannot be created.

The goal is to make the test pass.

**Comment by filipnavara** [comment]
Reported in CoreFX as https://github.com/dotnet/corefx/issues/36538.

**Comment by filipnavara** [comment]
Should be fixed with next CoreFX bump.

**Comment by steveisok** [comment]
I think this may still fail for other reasons.  @MaximLipnin, can you please confirm?

**Comment by MaximLipnin** [comment]
The test still fails with the same exception (latest mono master 9a19bdb6e63590875e9ac80496720dd365611754 on macOS)

**Comment by filipnavara** [comment]
I'll recheck and reopen the CoreFX issue if necessary.

**Comment by filipnavara** [comment]
I can confirm the issue is still present. I updated the CoreFX issues but apparently I don't have the necessary rights to re-open it.

**Comment by filipnavara** [comment]
The bug in now fixed in https://github.com/dotnet/corefx/commit/a7efd2a2b3c638b5490547ad6beca128ba5d7bfe. Keeping this issue open until we do the next CoreFX version bump.
