### ISSUE TITLE
System.Native missing during install

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#15831]
## Steps to Reproduce

1. Install mono following the directions here: https://www.mono-project.com/download/stable/#download-lin WSL Ubuntu 18.04

### Current Behavior

Several times like this:
```
Setting up mono-gac (6.0.0.313-0xamarin3+ubuntu1804b1) ...
* Installing 1 assembly from libnunit-console-runner2.6.3-cil into Mono

Unhandled Exception:
System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
  at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <81342d83acda4c5590ec
19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& error
Info) [0x00007] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <81342d83acda4c5590ec19c7afdf26b9>
:0
```

### Expected Behavior

Not this.
Strongly suggest System.Native be linked into libmono and use icalls.
Like it used to be.

## On which platforms did you notice this

Linux

**Comment by MaxAlex** [comment]
I'm getting the same error on Ubuntu 16.04; 88 repetitions of the theme:

```
Unhandled Exception:
System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
  at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.File.Exists (System.String path) [0x00043] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at Mono.Tools.Driver.LoadConfig (System.Boolean quiet) [0x00028] in <23529d1919fc4cdeb9723008e6dfcc48>:0
  at Mono.Tools.Driver.Main (System.String[] args) [0x00351] in <23529d1919fc4cdeb9723008e6dfcc48>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
  at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at System.IO.File.Exists (System.String path) [0x00043] in <81342d83acda4c5590ec19c7afdf26b9>:0
  at Mono.Tools.Driver.LoadConfig (System.Boolean quiet) [0x00028] in <23529d1919fc4cdeb9723008e6dfcc48>:0
  at Mono.Tools.Driver.Main (System.String[] args) [0x00351] in <23529d1919fc4cdeb9723008e6dfcc48>:0
E: installing Assembly /usr/lib/cli/glade-sharp-2.0/glade-sharp.dll failed
E: Installation of libglade2.0-cil with /usr/share/cli-common/runtimes.d/mono failed
* Installing 1 assembly from libglib2.0-cil into Mono

```

**Comment by lemonmojo** [comment]
Same for me on macOS 10.14.6 when creating a new GUID.

**Comment by Lazyboy007** [comment]
Same issue on Ubuntu 18.04. Installed via apt and it now shows up as an error every time I run apt:

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 apt-utils : Depends: apt (= 1.6.11) but 1.6.1 is to be installed
 mono-devel : Depends: ca-certificates-mono (= 6.0.0.313-0xamarin3+ubuntu1804b1) but 5.16.0.220-0xamarin4+ubuntu1804b1 is to be installed
`

Yet running --fix-broken gives the error mentioned in the first post.

**Comment by directhex** [comment]
This issue typically happens if you have hand-edited /etc/mono/config on an old version, then upgraded to 6.x

Check whether you have a file /etc/mono/config.dpkg-new or similar - if so, replace /etc/mono/config with it and try again.

**Comment by jaykrell** [comment]
I never heard of this file.

**Comment by directhex** [comment]
@jaykrell /etc/mono/config is the default dllmap:

```
<configuration>
	<dllmap dll="i:cygwin1.dll" target="libc.so.6" os="!windows" />
	<dllmap dll="libc" target="libc.so.6" os="!windows"/>
	<dllmap dll="intl" target="libc.so.6" os="!windows"/>
	<dllmap dll="intl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
	<dllmap dll="libintl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
	<dllmap dll="libintl" target="libc.so.6" os="!windows"/>
	<dllmap dll="i:libxslt.dll" target="libxslt.so" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libodbc.so" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libiodbc.dylib" os="osx"/>
	<dllmap dll="oci" target="libclntsh.so" os="!windows"/>
	<dllmap dll="db2cli" target="libdb2_36.so" os="!windows"/>
	<dllmap dll="MonoPosixHelper" target="$mono_libdir/libMonoPosixHelper.so" os="!windows" />
	<dllmap dll="System.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
	<dllmap dll="System.Net.Security.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
	<dllmap dll="System.Security.Cryptography.Native.Apple" target="$mono_libdir/libmono-native.so" os="osx" />
	<dllmap dll="libmono-btls-shared" target="$mono_libdir/libmono-btls-shared.so" os="!windows" />
	<dllmap dll="i:msvcrt" target="libc.so.6" os="!windows"/>
	<dllmap dll="i:msvcrt.dll" target="libc.so.6" os="!windows"/>
	<dllmap dll="sqlite" target="libsqlite.so.0" os="!windows"/>
	<dllmap dll="sqlite3" target="libsqlite3.so.0" os="!windows"/>
	<dllmap dll="libX11" target="libX11.so.6" os="!windows" />
	<dllmap dll="libgdk-x11-2.0" target="libgdk-x11-2.0.so.0" os="!windows"/>
	<dllmap dll="libgdk_pixbuf-2.0" target="libgdk_pixbuf-2.0.so.0" os="!windows"/>
	<dllmap dll="libgtk-x11-2.0" target="libgtk-x11-2.0.so.0" os="!windows"/>
	<dllmap dll="libglib-2.0" target="libglib-2.0.so.0" os="!windows"/>
	<dllmap dll="libgobject-2.0" target="libgobject-2.0.so.0" os="!windows"/>
	<dllmap dll="libgnomeui-2" target="libgnomeui-2.so.0" os="!windows"/>
	<dllmap dll="librsvg-2" target="librsvg-2.so.2" os="!windows"/>
	<dllmap dll="libXinerama" target="libXinerama.so.1" os="!windows" />
	<dllmap dll="libasound" target="libasound.so.2" os="!windows" />
	<dllmap dll="libcairo-2.dll" target="libcairo.so.2" os="!windows"/>
	<dllmap dll="libcairo-2.dll" target="libcairo.2.dylib" os="osx"/>
	<dllmap dll="libcups" target="libcups.so.2" os="!windows"/>
	<dllmap dll="libcups" target="libcups.dylib" os="osx"/>
	<dllmap dll="i:kernel32.dll">
		<dllentry dll="__Internal" name="CopyMemory" target="mono_win32_compat_CopyMemory"/>
		<dllentry dll="__Internal" name="FillMemory" target="mono_win32_compat_FillMemory"/>
		<dllentry dll="__Internal" name="MoveMemory" target="mono_win32_compat_MoveMemory"/>
		<dllentry dll="__Internal" name="ZeroMemory" target="mono_win32_compat_ZeroMemory"/>
	</dllmap>
	<dllmap dll="gdiplus" target="libgdiplus.so.0" os="!windows"/>
	<dllmap dll="gdiplus.dll" target="libgdiplus.so.0"  os="!windows"/>
	<dllmap dll="gdi32" target="libgdiplus.so.0" os="!windows"/>
	<dllmap dll="gdi32.dll" target="libgdiplus.so.0" os="!windows"/>
</configuration>
```

If a user runs a Mono which is new enough to require System.Native, but their global dllmap does not include a mapping for it, things break. dpkg may cause this if it goes to unpack the new file, but sees that the old file is not pristine (i.e. the checksum on the file-on-disk does not match the checksum of the file from the version of the package which has been upgraded). This is assumed by the package manager to be intentional, and it leaves the conffile alone

**Comment by jaykrell** [comment]
Understood, but I don't think I changed it.
And still would prefer just to remove this dependency, for other reasons also.
But I've heard counterpoints. I'll have to PR it..

**Comment by TestVan** [comment]
> @jaykrell /etc/mono/config is the default dllmap:
> 
> ```
> <configuration>
> 	<dllmap dll="i:cygwin1.dll" target="libc.so.6" os="!windows" />
> 	<dllmap dll="libc" target="libc.so.6" os="!windows"/>
> 	<dllmap dll="intl" target="libc.so.6" os="!windows"/>
> 	<dllmap dll="intl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
> 	<dllmap dll="libintl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
> 	<dllmap dll="libintl" target="libc.so.6" os="!windows"/>
> 	<dllmap dll="i:libxslt.dll" target="libxslt.so" os="!windows"/>
> 	<dllmap dll="i:odbc32.dll" target="libodbc.so" os="!windows"/>
> 	<dllmap dll="i:odbc32.dll" target="libiodbc.dylib" os="osx"/>
> 	<dllmap dll="oci" target="libclntsh.so" os="!windows"/>
> 	<dllmap dll="db2cli" target="libdb2_36.so" os="!windows"/>
> 	<dllmap dll="MonoPosixHelper" target="$mono_libdir/libMonoPosixHelper.so" os="!windows" />
> 	<dllmap dll="System.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
> 	<dllmap dll="System.Net.Security.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
> 	<dllmap dll="System.Security.Cryptography.Native.Apple" target="$mono_libdir/libmono-native.so" os="osx" />
> 	<dllmap dll="libmono-btls-shared" target="$mono_libdir/libmono-btls-shared.so" os="!windows" />
> 	<dllmap dll="i:msvcrt" target="libc.so.6" os="!windows"/>
> 	<dllmap dll="i:msvcrt.dll" target="libc.so.6" os="!windows"/>
> 	<dllmap dll="sqlite" target="libsqlite.so.0" os="!windows"/>
> 	<dllmap dll="sqlite3" target="libsqlite3.so.0" os="!windows"/>
> 	<dllmap dll="libX11" target="libX11.so.6" os="!windows" />
> 	<dllmap dll="libgdk-x11-2.0" target="libgdk-x11-2.0.so.0" os="!windows"/>
> 	<dllmap dll="libgdk_pixbuf-2.0" target="libgdk_pixbuf-2.0.so.0" os="!windows"/>
> 	<dllmap dll="libgtk-x11-2.0" target="libgtk-x11-2.0.so.0" os="!windows"/>
> 	<dllmap dll="libglib-2.0" target="libglib-2.0.so.0" os="!windows"/>
> 	<dllmap dll="libgobject-2.0" target="libgobject-2.0.so.0" os="!windows"/>
> 	<dllmap dll="libgnomeui-2" target="libgnomeui-2.so.0" os="!windows"/>
> 	<dllmap dll="librsvg-2" target="librsvg-2.so.2" os="!windows"/>
> 	<dllmap dll="libXinerama" target="libXinerama.so.1" os="!windows" />
> 	<dllmap dll="libasound" target="libasound.so.2" os="!windows" />
> 	<dllmap dll="libcairo-2.dll" target="libcairo.so.2" os="!windows"/>
> 	<dllmap dll="libcairo-2.dll" target="libcairo.2.dylib" os="osx"/>
> 	<dllmap dll="libcups" target="libcups.so.2" os="!windows"/>
> 	<dllmap dll="libcups" target="libcups.dylib" os="osx"/>
> 	<dllmap dll="i:kernel32.dll">
> 		<dllentry dll="__Internal" name="CopyMemory" target="mono_win32_compat_CopyMemory"/>
> 		<dllentry dll="__Internal" name="FillMemory" target="mono_win32_compat_FillMemory"/>
> 		<dllentry dll="__Internal" name="MoveMemory" target="mono_win32_compat_MoveMemory"/>
> 		<dllentry dll="__Internal" name="ZeroMemory" target="mono_win32_compat_ZeroMemory"/>
> 	</dllmap>
> 	<dllmap dll="gdiplus" target="libgdiplus.so.0" os="!windows"/>
> 	<dllmap dll="gdiplus.dll" target="libgdiplus.so.0"  os="!windows"/>
> 	<dllmap dll="gdi32" target="libgdiplus.so.0" os="!windows"/>
> 	<dllmap dll="gdi32.dll" target="libgdiplus.so.0" os="!windows"/>
> </configuration>
> ```
> 
> If a user runs a Mono which is new enough to require System.Native, but their global dllmap does not include a mapping for it, things break. dpkg may cause this if it goes to unpack the new file, but sees that the old file is not pristine (i.e. the checksum on the file-on-disk does not match the checksum of the file from the version of the package which has been upgraded). This is assumed by the package manager to be intentional, and it leaves the conffile alone

Hi, I add link on my dllmap , but still get error. 
![20190815101258](https://user-images.githubusercontent.com/50074809/63141051-d7921780-c016-11e9-9c53-ff46d378f99b.png)
![20190815100033](https://user-images.githubusercontent.com/50074809/63141055-de208f00-c016-11e9-92cf-b4061b5d51fe.png)

**Comment by directhex** [comment]
This issue should be resolved in 6.0.0.319-0xamarin4

**Comment by TestVan** [comment]
> This issue should be resolved in 6.0.0.319-0xamarin4
  I install mono  by  yum install  mono-complete on centos ,   mono jit compiler version is  6.0.0.319, but still can't run successful.
![20190813142131](https://user-images.githubusercontent.com/50074809/63147320-4a5bbc80-c030-11e9-8d09-e2985a96d6ca.png)
![、20190815100230](https://user-images.githubusercontent.com/50074809/63147327-4def4380-c030-11e9-8d70-872775fe5ef1.png)

**Comment by directhex** [comment]
1) that dllmap has been edited, and isn't the one we ship `rpm -V mono-core` will likely confirm this
2) this bug is specifically for a scenario reported on Ubuntu, and doesn't apply on CentOS.

**Comment by TestVan** [comment]
> 1. that dllmap has been edited, and isn't the one we ship `rpm -V mono-core` will likely confirm this
> 2. this bug is specifically for a scenario reported on Ubuntu, and doesn't apply on CentOS.

Thanks for your patient, @directhex ,     reinstall mono again  and make dllmap  as  default, I still get the System.DllNotFoundException: System.Native error on  https://github.com/mono/mono/issues/16266,  how could make  C++ call C#  successfully on Centos7?
![20190817111637](https://user-images.githubusercontent.com/50074809/63206065-83536a00-c0e0-11e9-888e-12394b142fd8.png)
![20190817111832](https://user-images.githubusercontent.com/50074809/63206098-d9c0a880-c0e0-11e9-9cbd-07c7debe4db7.png)

**Comment by directhex** [comment]
What does `ldd /usr/lib64/libmono-native.so` report?

Also, run `export MONO_LOG_LEVEL=debug` and `export MONO_LOG_MASK=dll` before running your app, for more useful error logging.

**Comment by laeubi** [comment]
@directhex I have compiled mono from the latest git and facing the same error, I'm using the embedded mono and first call is `mono_set_dirs` to the custom install folder, output from the log is

```
Mono: DllImport attempting to load: 'System.Native'.
Mono: DllImport error loading library '/opt/mono/latest/lib/mono/4.5/System.Native': '/opt/mono/latest/lib/mono/4.5/System.Native: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/opt/mono/latest/lib/mono/4.5/libSystem.Native.so': '/opt/mono/latest/lib/mono/4.5/libSystem.Native.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/opt/mono/latest/lib/mono/4.5/libSystem.Native.so': '/opt/mono/latest/lib/mono/4.5/libSystem.Native.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
... some more attempts on other places ...
Mono: DllImport unable to load library 'System.Native'.
```

the dllmap looks like this:
```
<configuration>
	<dllmap dll="i:cygwin1.dll" target="libc.so.6" os="!windows" />
	<dllmap dll="libc" target="libc.so.6" os="!windows"/>
	<dllmap dll="intl" target="libc.so.6" os="!windows"/>
	<dllmap dll="intl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
	<dllmap dll="libintl" name="bind_textdomain_codeset" target="libc.so.6" os="solaris"/>
	<dllmap dll="libintl" target="libc.so.6" os="!windows"/>
	<dllmap dll="i:libxslt.dll" target="libxslt.so" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libodbc.so.2" os="!windows"/>
	<dllmap dll="i:odbc32.dll" target="libiodbc.dylib" os="osx"/>
	<dllmap dll="oci" target="libclntsh.so" os="!windows"/>
	<dllmap dll="db2cli" target="libdb2_36.so" os="!windows"/>
	<dllmap dll="MonoPosixHelper" target="$mono_libdir/libMonoPosixHelper.so" os="!windows" />
	<dllmap dll="System.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
	<dllmap dll="System.Net.Security.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
	<dllmap dll="System.Security.Cryptography.Native.Apple" target="$mono_libdir/libmono-native.so" os="osx" />
	<dllmap dll="libmono-btls-shared" target="$mono_libdir/libmono-btls-shared.so" os="!windows" />
	<dllmap dll="i:msvcrt" target="libc.so.6" os="!windows"/>
	<dllmap dll="i:msvcrt.dll" target="libc.so.6" os="!windows"/>
	<dllmap dll="sqlite" target="libsqlite.so.0" os="!windows"/>
	<dllmap dll="sqlite3" target="libsqlite3.so.0" os="!windows"/>
	<dllmap dll="libX11" target="libX11.so.6" os="!windows" />
	<dllmap dll="libgdk-x11-2.0" target="libgdk-x11-2.0.so.0" os="!windows"/>
	<dllmap dll="libgdk_pixbuf-2.0" target="libgdk_pixbuf-2.0.so.0" os="!windows"/>
	<dllmap dll="libgtk-x11-2.0" target="libgtk-x11-2.0.so.0" os="!windows"/>
	<dllmap dll="libglib-2.0" target="libglib-2.0.so.0" os="!windows"/>
	<dllmap dll="libgobject-2.0" target="libgobject-2.0.so.0" os="!windows"/>
	<dllmap dll="libgnomeui-2" target="libgnomeui-2.so.0" os="!windows"/>
	<dllmap dll="librsvg-2" target="librsvg-2.so.2" os="!windows"/>
	<dllmap dll="libXinerama" target="libXinerama.so.1" os="!windows" />
	<dllmap dll="libasound" target="libasound.so.2" os="!windows" />
	<dllmap dll="libcairo-2.dll" target="libcairo.so.2" os="!windows"/>
	<dllmap dll="libcairo-2.dll" target="$mono_libdir/libcairo.2.dylib" os="osx" />
	<dllmap dll="libcups" target="libcups.so.2" os="!windows"/>
	<dllmap dll="libcups" target="libcups.dylib" os="osx"/>
	<dllmap dll="i:kernel32.dll">
		<dllentry dll="__Internal" name="CopyMemory" target="mono_win32_compat_CopyMemory"/>
		<dllentry dll="__Internal" name="FillMemory" target="mono_win32_compat_FillMemory"/>
		<dllentry dll="__Internal" name="MoveMemory" target="mono_win32_compat_MoveMemory"/>
		<dllentry dll="__Internal" name="ZeroMemory" target="mono_win32_compat_ZeroMemory"/>
	</dllmap>
	<dllmap dll="gdiplus" target="libgdiplus.so.0" os="!windows"/>
	<dllmap dll="gdiplus.dll" target="libgdiplus.so.0"  os="!windows"/>
	<dllmap dll="gdi32" target="libgdiplus.so.0" os="!windows"/>
	<dllmap dll="gdi32.dll" target="libgdiplus.so.0" os="!windows"/>
</configuration>
```

I tried to "help" mono a bit an symlinked the `libmono-native.so` to  `lib/mono/4.5/System.Native` then the log entry changes to

Mono: DllImport error loading library '/opt/mono/latest/lib/mono/4.5/System.Native': '/opt/mono/latest/lib/mono/4.5/System.Native: undefined symbol: mono_add_internal_call_with_flags'.

so maybe this is not really something not found but mono actually finds the lib but can't load it?
