### ISSUE TITLE
[netcore] Performance: Buffer.Memmove is slow

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16592]
`Buffer.Memmove` is used by `Buffer.BlockCopy` and many `String` APIs, such as `Substring` so the effect of the slow implementation is quite visible. [Benchmarks](https://gist.github.com/filipnavara/e8c0f022250af437bc4bf8fdec68a815) show significantly worse performance for `Buffer.BlockCopy` and `String.Substring` APIs when comparing Mono w/ LLVM JIT and CoreCLR.

**Comment by filipnavara** [comment]
Partially fixed by https://github.com/mono/mono/pull/16609.

**Comment by filipnavara** [comment]
A more comprehensive fix in #16610.

**Comment by EgorBo** [comment]
Fixed in https://github.com/mono/mono/pull/16610

**Comment by filipnavara** [comment]
I was waiting for #16609 to close this issue. You fixed the LLVM JIT but there is still an issue that should be fixed for regular mini JIT.
