### ISSUE TITLE
[iOS] HttpClientHandler.ServerCertificateCustomValidationCallback support missing

### ISSUE THREAD

**Issue by chamons** [mono/mono#17125]
According to 

https://github.com/xamarin/xamarin-android/issues/3682

and discussions online, the `HttpClientHandler.ServerCertificateCustomValidationCallback` API works on Xamarin.Android but not Xamarin.iOS.

There is a [new and old handler](https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-536105796) internally inside mono, and iOS is using the old one currently.

There is some interest in it working across platforms (see [feedback](https://developercommunity.visualstudio.com/content/problem/735045/xamarin-ios-servicepointmanager-servercertificatev.html?childToView=748890#comment-748890)).

**Comment by akamud** [comment]
I thought this was fixed in https://github.com/xamarin/xamarin-macios/issues/4170. I'm really confused about the support in this case. You have to read a bunch of issues in different repos to get an idea of what's happening and it still is not 100% clear.

**Comment by steveisok** [comment]
@chamons We are working to make it the same for both platforms. 

@akamud Long story short, we released for Android first and need to follow up w/ iOS.  My apologies for the confusion.

**Comment by akamud** [comment]
Thanks for the clarification @steveisok. Do you plan to put this in Xamarin documentation anywhere when it is released in both platforms?

**Comment by damianun** [comment]
@steveisok does it mean you will be changing HttpClient in macios to update it to use CoreFx implementation as it was done for Android[(Mono GitHub PR 13338)?](https://github.com/mono/mono/pull/13338)

**Comment by baulig** [comment]
> @steveisok does it mean you will be changing HttpClient in macios to update it to use CoreFx implementation as it was done for Android[(Mono GitHub PR 13338)?](https://github.com/mono/mono/pull/13338)

Yes, that's the plan.  There shouldn't really be two different and incompatible implementations on our mobile profiles.

**Comment by mepurush** [comment]
Is this fix available in OCT 28 update VS 2019 for Mac version 8.3.5(8.3.5.13)?

**Comment by steveisok** [comment]
@mepurush Not yet. I'll update when the fix comes in.

**Comment by wcoder** [comment]
Checked `ServicePointManager.ServerCertificateValidationCallback` with `HttpClientHandler ` -
working on iOS, but still not on Android.

<details><summary>System info</summary>
<p>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3.8 (build 8)
Installation UUID: 86a2c294-040d-4499-b1d2-907a97889793
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.2.1 (15526.1)
Build 11B500

=== Xamarin.Mac ===

Version: 6.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400

=== Xamarin.iOS ===

Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin.Android ===

Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/ypakala/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ypakala/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-06 18:31:30 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-06 18:31:50 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803080008
Git revision: 51ddc17b26f5a73f6e2a47feeb38bf1270662527
Build date: 2019-11-06 21:50:59+00
Build branch: release-8.3
Xamarin extensions: 010ea9b96369b2de32742f30576e92840acd1fac

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.6.0
BinObjCleaner 1.5

```

</p>
</details>

**Comment by akamud** [comment]
From my understanding the point is not to support `ServicePointManager` anymore, the point is to support `HttpClientHandler.ServerCertificateCustomValidationCallback`, which is already working on Android as https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-535679023 suggests.

**Comment by steveisok** [comment]
Correct.  We are in the process of updating ios

**Comment by Cybrosys** [comment]
Could you perhaps explain how the manged HttpClientHandler and the validation callback interacts with the recommendation per platform, which is to use:
iOS - NSUrlSession
Android - AndroidClientHandler
?

Does the new HttpClientHandler decorate the recommendations per platform, or is it the normal managed HttpClientHandler with TLS 1.2+ support, which was missing.?

**Comment by lilleydnSub** [comment]
I have seen this issue on a Mac App, Will the iOS Fix will also Fix it for the Mac too ?  Or do we need a separate Issue ?

**Comment by Cybrosys** [comment]
Excuse me for tagging you both @steveisok @baulig , but, I'm really interested in knowing how we should treat NSUrlSession and AndroidClientHandler now that ServicePointManager is no longer the "central" way of doing custom certificate validation.

The Xamarin project properties allows me to specify which HttpClient implementation/stack should be the default in my projects.
[HttpClient and SSL/TLS implementation selector for iOS/macOS](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/http-stack?context=xamarin/cross-platform)
[HttpClient Stack and SSL/TLS Implementation Selector for Android](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows)

If I have to manually instantiate NSUrlSession or AndroidClientHandler and hook into the validation callbacks available for each, then there's no meaning in being able to configure the HttpClient technology stack from the project properties of Xamarin projects.

From what I've seen, we're supposed to use the mangaed HttpClientHandler, instead of NSUrlSession and AndroicClientHandler, if we want to do custom certificate validation, but isn't that against the recommendation, since it doesn't support TLS1.2+ (according to the above linked pages)?

Maybe I'm just confused? Maybe the HttpClientHandler uses NSUrlSession and/or AndroidClientHandler internally? Please, I would appreciate it if you could clarify this for me.

**Comment by baulig** [comment]
> Excuse me for tagging you both @steveisok @baulig , but, I'm really interested in knowing how we should treat NSUrlSession and AndroidClientHandler now that ServicePointManager is no longer the "central" way of doing custom certificate validation.

There shouldn't really be anything special about `AndroidClientHandler` and the reason why `NSUrlSession` is special is because there were concerns about size.  A tradeoff had to be made between consistency and ease of use - and the additional size that would come from pulling in `X509Certificate` and some of the related crypto code.
 
> The Xamarin project properties allows me to specify which HttpClient implementation/stack should be the default in my projects.
> [HttpClient and SSL/TLS implementation selector for iOS/macOS](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/http-stack?context=xamarin/cross-platform)
> [HttpClient Stack and SSL/TLS Implementation Selector for Android](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows)
> 
> If I have to manually instantiate NSUrlSession or AndroidClientHandler and hook into the validation callbacks available for each, then there's no meaning in being able to configure the HttpClient technology stack from the project properties of Xamarin projects.

Hooking into the validation callbacks is not something that you should use on a regular basis - and especially using it with `NSUrlSession` is highly discouraged.  Whenever possible, the OS-based mechanism for trusting certificates should be used - see [https://support.apple.com/en-us/HT204477](https://support.apple.com/en-us/HT204477).

> From what I've seen, we're supposed to use the mangaed HttpClientHandler, instead of NSUrlSession and AndroicClientHandler, if we want to do custom certificate validation, but isn't that against the recommendation, since it doesn't support TLS1.2+ (according to the above linked pages)?

I'm not sure what you mean with the "managed HttpClientHandler" - I think you're confusing this with the old legacy TLS provider.

> How can I hook into the certificate validation when I'm not the one instantiating the HttpClient instance. There are some frameworks or code that does that internally and since the ServicePointManager is no longer the "central" override, how can I work around this issue?

You mean you're not the one instantiating the `HttpClientHandler` instance?

This is exactly the same situation as with any of the other `HttpClientHandler` properties (except that a custom certificate validation callback should only be used under very exceptional circumstances), you also have to manually construct the handler to set any of these.

The UI switcher is just a convenient way to define a "default" behavior - and to answer the question what `new HttpClient ()` should do.

> I also wonder why the validation callback is on the handler and not on the HttpClient instance? It would make more sense to have it on the HttpClient as you can't access the HttpClientHandler from a HttpClient instance.

That's an API decision that has been made by the .NET Core Team.  I do now know their reasoning behind it, but I would imagine it has been done for consistency and simplicity.  Just imagine for a second that those properties were on the `HttpClient` instance (or the `HttpClientHandler` was accessible from `HttpClient`) - it'd immediately open up the question what should happen if you set any of them after any request has already been sent.  If you send multiple requests to the same URL, the connection may also be kept open internally for reuse, but what if you were able to modify any connection properties (such as for instance `Proxy`) after sending a request?

The way the API is designed at the moment, you need to set all those properties prior to initializing the `HttpClient` - so once the first request has been initiated, the state that's controlled by those properties won't change.

> Maybe I'm just confused? Maybe the HttpClientHandler uses NSUrlSession and/or AndroidClientHandler internally? Please, I would appreciate it if you could clarify this for me.

Both are just implementation of the `HttpMessageHandler` class - which is the base class of `HttpClientHandler`.  The reason why `NSUrlSession` is based on `HttpMessageHandler` (and not `HttpClientHandler`) is to reduce app size on iOS.

> Considering how ServicePointManager worked/was used, why wasn't a static callback just added to the HttpClient class. You would've gotten rid of ServicePointManager and its assembly, while still adding a equivalent solution .

We want to keep compatibility with .NET Core both on the API as well as on the feature level.  So adding a new static callback to a public class is something that needs to be discussed with .NET Core's API team.

I hope this answers your questions and concerns, if not then just let us know and we'll gladly help.

**Comment by subsembly** [comment]
Thanks for the long explanation. One thing that is still not clear to me is, what implementation do I get when I just call

HttpClientHandler aHandler = new HttpClientHandler();

in my shared code? Any chance to get an AndroidClientHandler, NSUrlSessionHandler, or CFNetworkHandler. Have the Xamarin project properties any influence here?

Is there any other way to instantiate a default (maybe controlled by Xamarin project properties) HttpClientHandler in a platform independent way?

**Comment by baulig** [comment]
The Apple based handlers - `NSUrlSessionHandler` and `CFNetworkHandler` - are just implementations of the `HttpMessageHandler` class (see it's [API docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=netcore-3.0)).

The `HttpMessageHandler` is an abstract class containing ([`SendAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler.sendasync?view=netcore-3.0#System_Net_Http_HttpMessageHandler_SendAsync_System_Net_Http_HttpRequestMessage_System_Threading_CancellationToken_)):

```
protected internal abstract Task<HttpResponseMessage> SendAsync (HttpRequestMessage request, CancellationToken cancellationToken);
```

The `AndroidClientHandler` derives from `HttpClientHandler` (which derives from `HttpMessageHandler` as well).

Instantiating a new `HttpClientHandler` with

```
new HttpClientHandler ()
```

gets you a platform-specific implementation that you cannot change.  On all platforms except Windows, it's using the [`SocketsHttpHandler`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.0l) internally.

The Xamarin project properties only affect what's happening when you instantiate `HttpClient` with it's default constructor, that is

```
new HttpClient ()
```

**Comment by wcoder** [comment]
@subsembly 

> in my shared code? Any chance to get an AndroidClientHandler, NSUrlSessionHandler, or CFNetworkHandler. Have the Xamarin project properties any influence here?

yes, you can do this via reflection, but it's **not safe** because the internal implementation can be changed in future:
https://github.com/Softeq/XToolkit.WhiteLabel/blob/ffbf01a330a1555385b1080613fa78e088ed5cfc/Softeq.XToolkit.Remote/Client/HttpMessageHandlerBuilder.cs#L106-L107

**Comment by wcoder** [comment]
@baulig 

> Instantiating a new HttpClientHandler with `new HttpClientHandler ()` gets you a platform-specific implementation that you cannot change. 

Why is that so? Who will change the new instance of `HttpClientHandler` to native implementation?

As I know only `new HttpClient()` can create a platform-specific handler under the hood because it has an internal method `CreateDefaultHandler` for this.

**Comment by baulig** [comment]
> Why is that so? Who will change the new instance of `HttpClientHandler` to native implementation?

All of the following are _implementations_ of the `HttpMessageHandler` class:

- `HttpClientHandler`
- `NSUrlSessionHandler`
- `CFNetworkHandler`
- `AndroidClientHandler`

The UI switcher only controls which of the above mentioned implementations is used (in `CreateDefaultHandler()`) if you do `new HttpClient()`.

_Internally_ - but that is an internal implementation detail that you should not reply upon - the following are implementations of the `HttpMessageHandler` class as well:

- `SocketsHttpHandler` (public API in both .NET Core and Mono)
- `CurlHandler` (internal class in .NET Core that's not exposed via public API - we don't use it on Mono)
- `DelegatingHandler` (internal class, not exposed via public API)
- `DiagnosticsHandler` (internal class used for debugging, .NET Core only)
- `WinHttpHandler` (.NET Core only)

_Also internally_ - again this is an implementation detail that you should not rely upon - the `HttpClientHandler` constructs an "internal handler".  So on .NET Core, the user-visible instance is `HttpClientHandler` - but it may use different backends (`SocketsHttpHandler` or `CurlHandler`).

I know it's very confusing, so if you have any further questions, please do not hesitate to ask.

**Comment by subsembly** [comment]
Thank you very much for all your answers.  I think I understand clearly now.

We are using new HttpClientHandler() and install a ServerCertificateCustomValidationCallback.  As I understand now, we should get the SocketsHttpHandler on iOS, macOS, and Android.  Yet, on iOS and macOS our HttpClientHandler.ServerCertificateCustomValidationCallback is never called, however on Android it is called.

We hope that a fix for this will soon be available for macOS and iOS.

Thanks again.

**Comment by WilliamWatterson86** [comment]
@baulig  So should this be fixed now on iOS? or are we still waiting for a fix?

**Comment by Cybrosys** [comment]
@baulig Thank you for the very detailed reply!

To answer your question, I am in control of the instantiation of the `HttpClient`. It's in a Shared project between a iOS and Android project. I was hoping to avoid having platform specific code there, and instead rely on the underlying logic in `CreateDefaultHandler`. There was/is conflicting and confusing information online as to which implementation of `HttpMessageHandler` is recommended to be used per platform, hence why I wished for the validation callback to be on the `HttpClient`.

But, as it seems, you can't have custom certificate validation without also having to choose which `HttpMessageHandler` to use.

**Comment by janschoelchAtOK** [comment]
Is there any update on this @baulig? The `HttpClientHandler.ServerCertificateCustomValidationCallback` still doesn't seem to fire on iOS
