### ISSUE TITLE
OpenFileDialog, buttons icons are broken 

### ISSUE THREAD

**Issue by onekk** [mono/mono#17493]
## Steps to Reproduce

1. Open the new file dialog  
2. icons on buttons are missing on right of the filename, the buttons are present but invisible, when passing over with the mouse the buttons are shown (like a ghost) but the icons are missing
## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:
Devuan 9.0 Ascii - (Debian Stretch)

Latest repo for Debian Stretch used

**Comment by onekk** [comment]
No news?

The problem is still  present.

**Comment by filipnavara** [comment]
@onekk Essentially whole WinForms are on community support. If someone decides to peek into this and manages to reduce it to a test case that shows something in System.Drawing is broken I will be happy to look into it.

**Comment by onekk** [comment]
The test is fairly easy, use an open file dialog and you will not see the icons in the toolbar.

Tested on Debian 9 and even Ubuntu 18, someone has managed to iron out the problem for Ubuntu 18 downgrading to lbgdiplus 6.0.2 and identifiying the problem in the line 175 of
 
https://github.com/mono/mono/blob/master/mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs

`imageListTopToolbar.ColorDepth = ColorDepth.Depth32Bit;`

Unfortunately for Debian 9 there is no "libgdiplus 6.0.2" it bump from 5.6.2 or similar to 6.0.4.

As graphics interfaces are most common in mono having some "base features" like open file dialog broken is not "a minor annoyance", leaving it broken and left to a "community fix" is not very promising.

Regards

Carlo D.

**Comment by filipnavara** [comment]
I totally understand your frustration and I am aware of the steps to reproduce the problem with WinForms. The problem is that there is way too many code layers between the OpenFileDialog and the libgdiplus code. Someone has to analyze the problem and remove those layers, eg. reduce it to something that uses just painting and `ImageList`. In the next step remove even the `ImageList` and replace it with the code from it that triggers the problem. This is tedious process that takes time, unfortunately.

**Comment by onekk** [comment]
Many thanks, for the reply, at least the post is not dead.

For the slowness, no problem, if the problem is analyzed is a good starting point.

I couldn't test the downgrading to libgdiplus 6.0.2 that the programmer of the software that i use CamBam has found as resolutive, here the relevant post.

[http://www.cambam.co.uk/forum/index.php?topic=8254.msg65614#msg65614](url)

My main concern is that OpenFileDialog is not a "minor feature" every program that had to manage with files use it (at least if the interface is not rewritten from scratch), plus many icons are corrupted, in old versions there many libpng warnings, but all was working, now no more warning but the icons are corrupted, some program icons are with a purple background, and those in the OpenFileDialog are completely missing..

Speaking of distribution, Debian 9 is not a minor one, as is the base for many other Linux distribution around, and also Ubuntu 18 is concerned by the same bug.

I haven't the skills (and not even a decent machine to compile libraries from scratch) to do the "bug hunting", but if I could help in something, just ask.

**Comment by RussKie** [comment]
Is the issue specific to the dialog or other uses of icons on buttons affected?
Is Mono building on top of CoreFx?

For instance, in WinForms we had issues reported with icons (https://github.com/dotnet/winforms/issues/1825, https://github.com/dotnet/winforms/issues/2155) which were caused by a bug in CoreFx (fixed in https://github.com/dotnet/corefx/issues/41068).

**Comment by onekk** [comment]
I don't know how Mono is build, but in some programs there are problem with other icons in the interface, using Windows Form on Mono.

see

![icons](https://user-images.githubusercontent.com/7129964/70252888-74252480-1782-11ea-9c57-91603ffd4770.png)

**Comment by filipnavara** [comment]
I gave this another try today but I was unable to reproduce the issue on my setup (WSL w/ Ubuntu 18.04, latest Mono and libgdiplus packages, VcXsrv as X server). The icons appear just fine.

**Comment by onekk** [comment]
I have to check in the other distribution I have, now I'm using Artix Linux (Arch Linux) with mono 6.4.0.198 and lbgdiplus  libgdiplus 5.6.1-2 (quite "old" but some hints on the revelant pages, say that it is keep at this version for compatibility problems).

In the other installation, that i cannot test now there is the "latest" build from the mono site, for debian.

Maybe I'm not the only one that is having this problems, as generaly Arch Linux is using quite  bleeding edge software.

I will check ASAP on my debian with the latest mono and let you know.

Regards

Carlo D.

**Comment by filipnavara** [comment]
It is likely some combination of dependent libraries (libgdiplus dependenciesm particularly Cairo) and/or X server configuration that makes this happen. I'd like to get to the bottom of it but so far I had no success reproducing it locally on Windows/Mac/WSL.

**Comment by filipnavara** [comment]
Minor update: I managed to reproduce it locally. I still don't know exactly what causes it and how I triggered it but I can try to track it down.

**Comment by filipnavara** [comment]
Turns out this is a bug that I already fixed last year - https://github.com/mono/libgdiplus/commit/c98de971e5f453f50f898494b7791feb02302f62 (https://github.com/mono/libgdiplus/pull/604). The fix just newer made it to release.

**Comment by onekk** [comment]
So it is definitely a bug that is showing only in some conditions?

I've checked and seems that in the latest mono on debian, is present.

Regards

Carlo D.

**Comment by filipnavara** [comment]
> So it is definitely a bug that is showing only in some conditions?

It happens with libgdiplus 6.0.4 but it is fixed on GIT master version of libgdiplus. There are just no released binaries.

**Comment by dsvq** [comment]
This issue is either still present or resurgent.  It can be reproduced on CentOS 7, Mono JIT compiler version 6.12.0.90 (tarball Fri Sep  4 13:46:01 UTC 2020), with a one-liner program that merely shows an OpenFileDialog.

**Comment by InklingGirl** [comment]
Can confirm this is still an issue, on Ubuntu 22.04.2 after following the compilation instructions for [this project](https://github.com/jewalky/UltimateDoomBuilder).

**Comment by InklingGirl** [comment]
Bump.

**Comment by alligatorshoes** [comment]
Bumping this also. Experiencing this issue on SubtitleEdit:

```
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.2 Wed Jun 30 05:34:49 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
