### ISSUE TITLE
Two this entries in local window when debugging Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [mono/mono#19306]
Repro steps:
- Install VS 2019 16.6 Preview 2
- Create a new Blazor WebAssembly app
- Put a breakpoint in Counter.razor on `IncrementCount`
- F5
- Select the counter button to hit the break point
- Inspect the locals window

Expected result:
- Single `this` entry in the locals window

Actual result:
- Two `this` entries:

![image](https://user-images.githubusercontent.com/1874516/77488823-8e4b4700-6df3-11ea-8abd-efd28f4a79bc.png)

@lewing

**Comment by lewing** [comment]
@radical any idea what is going on here?

**Comment by lewing** [comment]
I haven't been able to reproduce this with recent builds, @radical has you resolved this?

**Comment by radical** [comment]
Yep, this is fixed.

**Comment by danroth27** [comment]
@lewing @radical I'm still seeing this issue with our latest Blazor WebAssembly builds:

![image](https://user-images.githubusercontent.com/1874516/78702944-4251d500-78be-11ea-8b8b-ea9b78b04ce5.png)

**Comment by lewing** [comment]
This is being addressed in the adaptor.  We'll review what we're doing in light of that as well.

https://github.com/microsoft/vscode-js-debug/commit/fd6f258ec9968d61639a082ed02e49b0f249fe44#diff-cdcd5151e5112d6fd91ce4c55714c3ceR284

**Comment by lewing** [comment]
fixed in vscode-js-debug
