### ISSUE TITLE
[sdks] runtime doesn't link with Xcode 11.4 due to weak import symbol ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by lewurm** [mono/mono#19393]
How to reproduce:
```console
$ git clone mono && cd mono
$ git submodule update --init --recursive
$ xcodebuild -version
Xcode 11.4
Build version 11E146
$ XCODE_DIR=`xcode-select -p` ENABLE_IOS=1 make -C sdks/builds -j build-ios-target64 
[...]
  CCLD     libmonosgen-2.0.la
ld: warning: -undefined dynamic_lookup is deprecated on iOS
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [libmonosgen-2.0.la] Error 1
```
This breaks the Xamarin.iOS build when building with `MONO_BUILD_FROM_SOURCE=1` set (which is only a developer option, but eventually we will have to deal with it).

Unity hits a similar issue on macOS: https://forum.unity.com/threads/empty-project-fails-to-compile-using-il2cpp-unity-2019-3-7-case-1231096.854743/ and https://forum.unity.com/threads/il2cpp-macstandalone-and-xcode-11-4.855187/

The suggested solution is to update macOS to at least 10.15.4, but that doesn't help for the iOS case.

Also I tried to bump the iOS min version to 13.4 (which needs some tiny fix around logging; just take the implementation for watchOS in the same file):
https://github.com/mono/mono/blob/a17ab75deac5096f402cd959c1b87e21a2c17aa6/sdks/versions.mk#L26
It doesn't help either (and anyway we could only go as far as 10.3 due to iOS/armv7).

Not sure what to do about it.

/cc @rolfbjarne @spouliot @akoeplinger

**Comment by lewurm** [comment]
command line helper to identify the offenders:
```console
$ find sdks/builds/ios-target64-release -name '*.a' | xargs nm | grep -C 10 set_overflow
```
The dependency is injected by some macros, originating from `usr/include/sys/_types/_fd_def.h` in the Xcode library. It contains the weak import definition of `__darwin_check_fd_set_overflow` too.

This patch makes it build, but obviously this will break things: https://gist.github.com/lewurm/6bc45386f1bc1de6b85dc6375bf8dd83

I would argue it's a Xcode bug.

**Comment by spouliot** [comment]
Better file this with Apple along with a sample. You'll not get an immediate fix/answer (even less outside the beta period), still worth filing it (since we might have to bump to a new Xcode, like 12, soonish).

**Comment by imhameed** [comment]
Why do we use `no_weak_imports` at all? Is the goal to avoid inadvertently depending on symbols which may only conditionally be available at runtime, depending on the OS version (see, for example: https://patches.libav.org/patch/63022/)?

**Comment by lewurm** [comment]
Reported it to Apple with a minimal repro:
* https://gist.github.com/lewurm/210b320cb6037ca8ad4a370adf1bde11
* https://feedbackassistant.apple.com/feedback/7647406
* https://openradar.appspot.com/FB7647406


> Why do we use `no_weak_imports` at all? Is the goal to avoid inadvertently depending on symbols which may only conditionally be available at runtime, depending on the OS version (see, for example: https://patches.libav.org/patch/63022/)?

Good question.  I guess it's a safeguard for us, but it might as well work without it. It's building fine, I'm gonna try it with XI master and report back.

**Comment by lewurm** [comment]
> It's building fine, I'm gonna try it with XI master and report back.

A simple app works fine without `no_weak_imports` on device. I guess it's a workaround we can use for now, but would be still nice to have the issue fixed by Apple.

**Comment by lewurm** [comment]
> > It's building fine, I'm gonna try it with XI master and report back.
> 
> A simple app works fine without `no_weak_imports` on device. I guess it's a workaround we can use for now, but would be still nice to have the issue fixed by Apple.

patch for said workaround (in case you are stuck on that issue): https://gist.github.com/lewurm/c1d03115cd695b47885872138c05b63f

**Comment by lewurm** [comment]
Still happens with Xcode 11.4.1

**Comment by philippemnoel** [comment]
I'm getting this issue using clang to compile a C program, any ideas how to get around with it?

**Comment by akoeplinger** [comment]
@philippemnoel you can remove your usage of `FD_SET` and related macros, or remove the `-no_weak_imports` linker flag.

**Comment by dlenski** [comment]
Over at https://gitlab.com/openconnect/openconnect/-/issues/131, one of our users reported a similar issue with Xcode 11.4, which was apparently resolved with 11.4.1. :thinking: 

```
  CCLD     libopenconnect.la
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _cancellable_connect in libopenconnect_la-ssl.o
      _cmd_fd_set in libopenconnect_la-ssl.o
      _check_cmd_fd in libopenconnect_la-ssl.o
      _poll_cmd_fd in libopenconnect_la-ssl.o
      _cancellable_recv in libopenconnect_la-ssl.o
      _cancellable_send in libopenconnect_la-ssl.o
      _tun_mainloop in libopenconnect_la-mainloop.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libopenconnect.la] Error 1
make[1]: *** [libopenconnect.la] Error 1
make: *** [all] Error 2
```

**Comment by akoeplinger** [comment]
I don't see the issue when building for iOS x86_64 with Xcode 11.4.1 but still see it when building for arm64/armv7.

**Comment by maxbelanger** [comment]
Chiming in because I haven't seen another fix for this: we've managed to get this to work for downlevel Xcode versions by passing the following to `clang`: `-Wl,-U,___darwin_check_fd_set_overflow`.

Per `man ld`:
```
     -U symbol_name
                 Specified that it is ok for symbol_name to have no definition.  With -two_levelnamespace, the resulting symbol will be marked dynamic_lookup which
                 means dyld will search all loaded images.
```

**Comment by akien-mga** [comment]
For the reference, this issue still seems reproducible with Xcode 12.0.1 (at least for iOS arm64).

**Comment by lewurm** [comment]
I got a reply from Apple today:

> We have added availability annotiations to `__darwin_check_fd_set_overflow` to avoid the use of weak. It is now required to build with current deployment target if you want to use `-Wl,-no_weak_imports`, building with older deployment target fundamentally requires weak imports, it is not supported to combine that with that linker option. Please try building for macOS 11 target to verify that `-Wl,-no_weak_imports` works.
