### ISSUE TITLE
Mono 6.12 port for FreeBSD

### ISSUE THREAD

**Issue by nkosi23** [mono/mono#21236]
This issue is meant to track the porting effort of mono 6.12 for freebsd. Mono is essential to enable a .NET development environment for FreeBSD users since it is used being the scenes by Omnisharp. 

With all pieces falling into place [with the freebsd porting effort for .NET 5 and 6](https://github.com/dotnet/runtime/issues/14537), upgrading mono will be the last remaining piece before downstream projects like Omnisharp can provide official out-of-the-box support for FreeBSD. This goal of this issue is to track the creation of the mono 6.12 port for FreeBSD.

Because I heavily depend on this work being done, I have decided to take care of my own destiny by getting my hands dirty on this :smile:. I am happy to lead this effort (this will be my first FreeBSD port but I am not new to programming). If someone already leads it just raise your hands as my goal is not to take ownership away from anyone but to join forces :wink:. Before creating this, I've been going through the ticket system of FreeBSD and lurking it for months and no one seems to work on it actively.

The first step would be to understand the current strategy followed with the mono5.1 and 6.8 ports to mirror it with the 6.12 effort. Also if people already have work in progress for 6.12, they could get a public repo up and link to it from here so that all people interested in this can join forces.

The idea behind this effort, is also to put together a single source of truth for mono porting efforts on FreeBSD, because right now the information is scattered and hard to find, whether it relates to the non-trivial build process, or to the current efforts carried by people. Getting the port up-to-date will also make it easier for the core team to provide official FreeBSD support.

**Comment by Thefrank** [comment]
what doesn't work? building from MAIN/HEAD is fine with: gcc10 and `--disable-dtrace`
I does return a ton of `Your operating system's sysconf (3) function doesn't correctly report physical memory size!` during the build
`make check` looks like it has 1 failure:
```
[utf8]
  g_utf16_to_utf8: OK
  g_utf8_to_utf16: OK
  g_utf8_to_utf16_with_nuls: OK
  g_utf8_seq: OK
  g_convert: FAILED (Failed to load content for UTF-8: Error opening file)
  g_unichar_xdigit_value: OK
  g_ucs4_to_utf16: OK
  g_utf16_to_ucs4: OK
  g_utf8_strlen: OK
  g_utf8_get_char: OK
  g_utf8_next_char: OK
  g_utf8_validate: OK
  g_utf8_strup: OK
  g_utf8_strdown: OK
  13 / 14 (92.8571%)
```
It DOES stop there however. So I am guessing that is fatal test failure and the build output is not viable. I have nothing to compare it to because https://jenkins.mono-project.com/job/test-mono-mainline-community/label=freebsd-12-amd64 is timing out for me

**Comment by nkosi23** [comment]
There are existing patches [in the ports tree for mono6.8](https://cgit.freebsd.org/ports/tree/lang/mono6.8/files) that will probably be helpful to get some tests pass. The mono6.8 port uses monolite to bootstrap, but I have just installed the mono6.8 package for time being.

The build is currently in progress on my machine, I will look into the tests too once it's done! I'm sure you didn't mean them to be helpful, but your comment on gcc and gmake saved me quite a few hours of head scratching :laughing:. While the build is in progress, I'll try to provide some porting documentation along the way as it is lacking:

# Create a fresh jail using BastilleBSD
There is a getting started guide on [using BastilleBSD](https://bastillebsd.org/getting-started/), however for simplicity some steps are not necessary here (such as isolating the jail network and creating a nat using pf). One can simply bootstrap a release 12.2:

`bastille bootstrap 12.2-RELEASE update`
 And then create a jail by attaching it directly to the main network interface:
`bastille create mono-porting-env 12.2-RELEASE 192.168.185.70 em0`

# Source code

One can either use git or the release tarballs provided by the mono project. I use the tarball here:

`fetch https://download.mono-project.com/sources/mono/mono-6.12.0.122.tar.xz`

# Build instructions

I am using the instruction for building mono on macOS [mentioned of the website of the mono project](https://www.mono-project.com/docs/compiling-mono/mac/) as a baseline, but adjustments are needed. Therefore to prepare the build environment one needs to run:

`pkg install install autoconf automake libtool pkgconf cmake python3 gcc gmake bash`

And then set the variables for the output directory of the build, and the version:
```
set PREFIX=/usr/local/mono-porting-dir/mono-6.12.0.122/build
set VERSION=6.12.0.122 
```

Then:
```
./configure --prefix=$PREFIX --disable-nls --disable-dtrace --build=amd64-freebsd12
gmake
gmake install
gmake mcs-do-tests
```

Right now I am at the first gmake... which just failed because bash also is a dependency :smile: . Adding it to the list above while typing this.

**Comment by akoeplinger** [comment]
> I have nothing to compare it to because jenkins.mono-project.com/job/test-mono-mainline-community/label=freebsd-12-amd64 is timing out for me

Unfortunately we had to move Jenkins behind a firewall for security reasons, here's what the current state there looks like:

![image](https://user-images.githubusercontent.com/1376924/136248689-f9b8d851-3ebb-4cb7-a4df-9aff2adbc0f0.png)

**Comment by nkosi23** [comment]
> Well, I 100% wanted to use LLVM/Clang but quickly found that to be impossible.
> 
> For tests try `gmake check -k` and that should run all the tests. The only test failures I saw were IPV6 related and I don't have IPV6 turned on in the build environment. There might be more but it put test results all over the place.
> 
> I assume you need the mono/mono version of MSBuild and not the microsoft mono version that ships inside dotnet?

Thanks a lot, I will try that as soon as I have a computer at hand! Indeed we need the mono/mono version of msbuild

**Comment by Thefrank** [comment]
mono, atleast from MAIN/HEAD seems stable-ish. I am not quite sure why FreeBSD ports only has up to 6.8. I guess its because so few things have mono as a dependency? The patches in ports were not required to build as I think most/all have already been merged in.

**Comment by nkosi23** [comment]
Okay so apparently, the entry point of mono/msbuild is build.sh, the shebang needs to be patched to use "/usr/bin/env bash" instead of "/bin/bash". Then when running the build I get:

```
./build.sh
Downloading 'https://dot.net/v1/dotnet-install.sh'
Trying to run 'curl https://dot.net/v1/dotnet-install.sh -sSL --retry 10 --create-dirs -o /usr/local/mono-porting/mono-msbuild/linux-packaging-msbuild-upstream-16.10.1-xamarinxplat.2021.05.26.14.00/.dotnet/dotnet-install.sh' for maximum of 5 attempts.
Ran 'curl https://dot.net/v1/dotnet-install.sh -sSL --retry 10 --create-dirs -o /usr/local/mono-porting/mono-msbuild/linux-packaging-msbuild-upstream-16.10.1-xamarinxplat.2021.05.26.14.00/.dotnet/dotnet-install.sh' successfully.
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.102/dotnet-sdk-5.0.102-freebsd-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.102/dotnet-sdk-5.0.102-freebsd-x64.tar.gz is not available.
dotnet_install: Error: Could not find `.NET Core SDK` with version = 5.0.102
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
Failed to install dotnet SDK from public location (exit code '1').
Failed to install dotnet SDK from public location (exit code '1').
```
So apparently, it tries to retrieve the .NET 5 SDK for FreeBSD, next step is to track down which script is doing that and pointing it to the releases of Sevarr/dotnetbsd for time being.

**Comment by nkosi23** [comment]
Nevermind, actually even simply  running the `dotnet` binary from the SDK I have downloaded (independently from the msbuild build process) returns this error, I will fix that first.

**Comment by Thefrank** [comment]
I took a quick look at mono/msbuild. I bumped the SDK requirement to 5.0.204 (the newest I have). Unless I am doing something wrong, it does not produce any non-NuGet packages:
```
root@dotnet5:~/msbuild/artifacts/packages/Release/Shipping # ll
total 4127
-rw-r--r--  1 root  wheel  1282416 Oct  7 18:27 Microsoft.Build.16.9.0.nupkg
-rw-r--r--  1 root  wheel   169637 Oct  7 18:27 Microsoft.Build.Framework.16.9.0.nupkg
-rw-r--r--  1 root  wheel   765520 Oct  7 18:27 Microsoft.Build.Runtime.16.9.0.nupkg
-rw-r--r--  1 root  wheel  1340619 Oct  7 18:27 Microsoft.Build.Tasks.Core.16.9.0.nupkg
-rw-r--r--  1 root  wheel   550626 Oct  7 18:27 Microsoft.Build.Utilities.Core.16.9.0.nupkg
```
Is that what you need?

**Comment by nkosi23** [comment]
@Thefrank if you have a linux machine, could you please install mono-complete (for mono 12.0) and tell me the content of your lib/mono/msbuild folder, and of your lib/mono/xbuild folder so that I can have a basis for comparison

**Comment by nkosi23** [comment]
Regarding the need to port msbuild, thinking about it again, if downloading the nuget packages from nuget was enough then why is the mono team maintaining its own fork of msbuild? There has to be something different between these builds. Could you please upload these nuget packages somewhere? And by the way, how did you even manage to build that, have you faced the nuget error I got?

**Comment by Thefrank** [comment]
So, to get MSBuild to build under FreeBSD I rolled the SDK requirement forward to the newest version I had. I didn't want to chance  it having broken/expired internal certs. The output on FreeBSD matches the output under Ubuntu 20.04 using `./build.sh -c Release --pack --publish --ci`. If you still want the nuget packages, let me know where you want them uploaded to.

**Comment by nkosi23** [comment]
Okay I just understood what the NuGet error actually means: the problem is that the package "Microsoft.DotNet.Arcade.Sdk" cannot be found in any of the feeds configured in Nuget.config. Which is weird since my NuGet feed already contains the arcade source:
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="arcade" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" />
    <add key="dotnet-public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />
    <add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
    <add key="dotnet3.1-symbols" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1-symbols/nuget/v3/index.json" />
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
    <add key="dotnet5-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json" />
  </packageSources>
  <disabledPackageSources />
</configuration>
```

For reference to other people, the arcade team provides [on their repository](https://github.com/dotnet/arcade#getting-started) the address of the NuGet feed on which their packages are published, along with [a link to browse the repository online](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-eng). The package is clearly present there, I have tried to set the version of the package to the latest version (7.0.0-beta.21508.1) in global.json but without success so far. I will keep digging into it.

**Comment by Thefrank** [comment]
errors like `Unable to load the service index for source ` are typically cert/auth errors.
when you bump the SDK version in `global.json` make sure that `./.dotnet` has the correct SDK unpacked in there.

**Comment by Thefrank** [comment]
FreeBSD 12.2+ uses `certctl`. if you manually added any certs make sure to rehash.

**Comment by nkosi23** [comment]
Well I added the cert mentioned in the dotnet core port issue, and I have just rehashed but it didn't help, same issue.
This makes me remember why I moved to FreeBSD, there were too many undocumented tricks and random showstoppers in the Windows world. But dotnet is worth it, and at least this time since it is open-source it should be much easier to maintain a stable config.

**Comment by Thefrank** [comment]
that is really confusing on why its still failing, ill have to look over my jail setup a bit more when I get some time

**Comment by nkosi23** [comment]
Just a gentle update to inform you that I may not be able to work on this for the next few weeks at least as I am in the midst of a pretty big personal and professional transition. However I remain committed and determined to get this port done!

**Comment by Thefrank** [comment]
well, the port system is able to build mono 6.13:
```
root@portsbuilder:/usr/ports/lang/mono6.13 # mono --version
Mono JIT compiler version 6.13.0.1201 (tarball Mon Oct 18 00:41:00 UTC 2021)
Copyright (C) Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          bigarrays softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Comment by Thefrank** [comment]
deleting `DST_Root_CA_X3.pem` should resolve the issue. Also make sure you have a `ISRG_Root_X1.pem`

**Comment by Thefrank** [comment]
Wait. Did that actually resolve the issue? Was it really an old cert + old bug?

**Comment by nkosi23** [comment]
@Thefrank sorry for the delay, I had to set up a new environment. So I just tried and unfortunately this does not solve the issue with building mono/msbuild :disappointed:  I am still getting the "Unable to load the service index" errors. Currently investigating...

**Comment by Thefrank** [comment]
@nkosi23 try seeing if turning on `allow_raw_sockets` or your jail managers version of that resolves the issue.

**Comment by nkosi23** [comment]
> @nkosi23 try seeing if turning on `allow_raw_sockets` or your jail managers version of that resolves the issue.

Unfortunately enabling raw sockets didn't help, the same error is still there.

**Comment by Thefrank** [comment]
most of the time, those errors come from using the source tarballs and not `git clone`

**Comment by Thefrank** [comment]
@nkosi23 
Short update: 
Mono 6.13 nightly still builds under FreeBSD 12.2
mono/msbuild does not appear to have any updates

**Comment by saper** [comment]
Thanks for the write up, it was very useful!

Here is my problem: trying to build [devel/msbuild](https://github.com/freebsd/freebsd-ports/tree/397a9456abbfdb8b44bb2ae688a2508a9fac3d6b/devel/msbuild) form ports using mono 5.10.1.57_3 and I am always getting:

```
============= MSBuild command =============
/big/ports/usr/ports/devel/msbuild/work/msbuild-0.06/build/../artifacts/mono-msbuild/msbuild "/big/ports/usr/ports/devel/msbuild/work/msbuild-0.06/build/Toolset.proj" /t:restore /m /clp:Summary /warnaserror /v:minimal /bl:"/big/ports/usr/ports/devel/msbuild/work/msbuild-0.06/build/../artifacts/Release-MONO/log/Toolset.binlog"
===========================================
Microsoft (R) Build Engine version 15.8.38.37692 (xplat-master/3c930fa8 Tue May  8 12:36:23 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: /m
```

I have even tried to bootstrap [mono msbuild v16.9.0](https://github.com/mono/msbuild/releases/tag/v16.9.0) and I am getting the same.

Is my mono too old? What is the problem? Just shifting arguments maybe (to get "mono" out of argv[0]?)

**Comment by Thefrank** [comment]
It has been about 2yr since I tried to build mono/msbuild but from what I recall, it does not build under the FreeBSD ports system anymore and was a pain to build outside of it.

I do have mono 6.12.0.199 from about a month ago: https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20230712 this does build under the ports system. There are patches for it that I have upstreamed into dotnet/runtime where they will eventually get backported to mono

**Comment by saper** [comment]
> I do have mono 6.12.0.199

Can we use it to update mono6.8 in ports? I have a small fix for 6.8 in the ports tree anyway.

> I am not quite sure that even "mono" msbuild is using mono anymore.

https://github.com/mono/msbuild/blob/de7a9c7b83f0cbfaedc0fc4cef3670755e0fc1f5/eng/cibuild_bootstrapped_msbuild.sh#L85

It is not so simple as just `/m:2`, I think my problem is not related to "too old" mono version at all.

**Comment by Thefrank** [comment]
using mono6.12 and building from a simple clone of the repo:
```
root@dotnet6:~/msbuild # ./eng/cibuild_bootstrapped_msbuild.sh --host_type mono
** Downloading MSBUILD from https://github.com/mono/msbuild/releases/download/v16.9.0/mono_msbuild_6.12.0.137.zip
Microsoft (R) Build Engine version 16.9.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Some command line switches were read from the auto-response file "MSBuild.rsp". To disable this file, use the "-noAutoResponse" switch.
/root/msbuild/eng/../artifacts/mono-msbuild/MSBuild.dll /fl /bl /clp:Summary /flp:v=diag /m /p:MSBuildExtensionsPath=/root/msbuild/eng/../artifacts/mono-msbuild/Extensions /p:MSBuildExtensionsPath32=/root/msbuild/eng/../artifacts/mono-msbuild/Extensions /p:MSBuildExtensionsPath64=/root/msbuild/eng/../artifacts/mono-msbuild/Extensions /p:DeterministicSourcePaths=false /p:MicrosoftNetCompilersVersion=3.9.0-5.21112.8 /p:NuGetBuildTasksVersion=5.11.3-rc.2 /verbosity:minimal mono/build/update_bundled_bits.proj
  ** NuGet Microsoft.NET.Sdk version 3.1.400-preview.20365.20
  ** NuGet Microsoft.NET.Sdk.Razor version 3.1.6
  ** NuGet Microsoft.NET.Sdk.Web version 3.1.300-servicing.20216.7
  ** NuGet Microsoft.NET.Sdk.Publish version 3.1.300-servicing.20216.7
  ** NuGet Microsoft.NET.Sdk.Web.ProjectSystem version 3.1.300-servicing.20216.7
  ** NuGet ILLink.Tasks version 0.1.6-prerelease.20175.2
  ** NuGet NuGet.Build.Tasks.Pack version 5.11.3-rc.2
  ** NuGet FSharp.NET.Sdk version 1.0.4-bundled-0100
  ** NuGet Microsoft.NET.Build.Extensions version 3.1.400-preview.20365.20
  Add this to mono's tools/nuget-hash-extractor/download.sh:
                  MS_EXTN_VERSIONS="$MS_EXTN_VERSIONS 3.1.400-preview.20365.20" # https://raw.githubusercontent.com/dotnet/cli/501e11d928c21608999c934f0a7078570b688c6c/build/DependencyVersions.props
  ** NuGet Microsoft.DotNet.MSBuildSdkResolver version 5.0.300-servicing.21267.11
  Determining projects to restore...
  Restored /root/msbuild/mono/build/sdks_and_nugets/nuget-build-tasks/nuget-build-tasks.csproj (in 925 ms).
CSC : warning CS2008: No source files specified. [/root/msbuild/mono/build/sdks_and_nugets/nuget-build-tasks/nuget-build-tasks.csproj]
  nuget-build-tasks -> /root/msbuild/artifacts/bin/nuget-build-tasks/Debug/net472/nuget-build-tasks.dll
  Downloading 'https://dot.net/v1/dotnet-install.sh'
  Trying to run 'curl https://dot.net/v1/dotnet-install.sh -sSL --retry 10 --create-dirs -o /tmp/tmp.QXbCSqZm/dotnet-install.sh' for maximum of 5 attempts.
  Ran 'curl https://dot.net/v1/dotnet-install.sh -sSL --retry 10 --create-dirs -o /tmp/tmp.QXbCSqZm/dotnet-install.sh' successfully.
  dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.408/dotnet-sdk-5.0.408-freebsd-x64.tar.gz
curl : (22) The requested URL returned error : 404 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
  dotnet-install: The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.408/dotnet-sdk-5.0.408-freebsd-x64.tar.gz' is not available.
  dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Sdk/5.0.408/dotnet-sdk-5.0.408-freebsd-x64.tar.gz
curl : (22) The requested URL returned error : 404 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
  dotnet-install: The resource at primary link 'https://dotnetbuilds.azureedge.net/public/Sdk/5.0.408/dotnet-sdk-5.0.408-freebsd-x64.tar.gz' is not available.
dotnet_install : error : Could not find `.NET Core SDK` with version = 5.0.408 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
dotnet_install : error : Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj(68,9): error MSB3073: The command "/root/msbuild/mono/build/sdks_and_nugets/../get_sdk_files.sh /root/msbuild/mono/build/../../mono/dotnet-overlay/msbuild-bin" exited with code 1.

Build FAILED.

CSC : warning CS2008: No source files specified. [/root/msbuild/mono/build/sdks_and_nugets/nuget-build-tasks/nuget-build-tasks.csproj]
curl : (22) The requested URL returned error : 404 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
curl : (22) The requested URL returned error : 404 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
dotnet_install : error : Could not find `.NET Core SDK` with version = 5.0.408 [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
dotnet_install : error : Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support [/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj]
/root/msbuild/mono/build/sdks_and_nugets/update_sdks_and_nugets.proj(68,9): error MSB3073: The command "/root/msbuild/mono/build/sdks_and_nugets/../get_sdk_files.sh /root/msbuild/mono/build/../../mono/dotnet-overlay/msbuild-bin" exited with code 1.
    1 Warning(s)
    5 Error(s)
```

**Comment by saper** [comment]
@Thefrank FreeBSD port patches the DotNetBuildFromSource in two different ways, but it works https://cgit.freebsd.org/ports/tree/devel/msbuild/files/patch-build_build.sh

I have just submitted https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272961 to include the fix to avoid MSB1008 error mentioned above. It is not clear to me why it happens to me and not for everyone else, but here it is.

**Comment by Thefrank** [comment]
Interesting that `/m` does not work on its own. `-maxCpuCount` or `-m` should always use the detected number cpus. I know that dotNET on FreeBSD 13.1 had issues using detecting/using more that a single thread (FreeBSD 12.4 and 13.2 are fine). Glad you got it to work!
