### ISSUE TITLE
Install 504 server Errors

### ISSUE THREAD

**Issue by ozawakei** [mono/mono#21298]
I used yum commands to install the specific version for mono-complete from centos7-stable repo.
However, some files return “504 server Errors”, and I cannot download this mono-complete version.
How can I solve this issue?

## Steps to Reproduce
The commands I used are
```
rpmkeys --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
su -c 'curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo'
yum -y install mono-complete-[version]
```

### Current Behavior
some files are [Errno 14] HTTPS Error 504 - Gateway Timeout
The error logs are:
```
mono-complete-5.8.0.108
#12 11.26 Downloading packages:
#12 30.56 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmonosgen-2_0-1-5.8.0.108-0.xamarin.2.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 30.56 Trying other mirror.
#12 64.97 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-winforms-5.8.0.108-0.xamarin.2.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 64.97 Trying other mirror.


mono-complete-5.2.0.224
#12 29.52 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmono-2_0-1-5.2.0.224-0.xamarin.1.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 29.52 Trying other mirror.
#12 35.49 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-web-5.2.0.224-0.xamarin.1.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 35.49 Trying other mirror.

mono-complete-6.10.0.104
#12 25.61 https://download.mono-project.com/repo/centos7-stable/m/mono-core/ibm-data-db2-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 25.61 Trying other mirror.
#12 35.56 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmonosgen-2_0-devel-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 35.56 Trying other mirror.
#12 67.43 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-reactive-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 67.43 Trying other mirror.
#12 82.96 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-wcf-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 82.96 Trying other mirror.
#12 101.8 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-winfxcore-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 101.8 Trying other mirror.

mono-complete-6.12.0.107
#12 8.776 Downloading packages:
#12 29.08 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmonosgen-2_0-devel-6.12.0.107-0.xamarin.9.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 29.08 Trying other mirror.
#12 37.46 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-reactive-6.12.0.107-0.xamarin.9.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 37.46 Trying other mirror.
```

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Comment by akoeplinger** [comment]
Should be fixed now, see https://github.com/mono/mono/issues/21273#issuecomment-963127516

**Comment by ozawakei** [comment]
Thank you for your confirmation.
However, these files still throw error.

```
mono-complete-5.8.0.108
#12 39.41 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-winforms-5.8.0.108-0.xamarin.2.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 39.41 Trying other mirror.
#12 39.43

mono-complete-5.2.0.224
#12 27.42 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmono-2_0-1-5.2.0.224-0.xamarin.1.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 27.42 Trying other mirror.
#12 34.00 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-web-5.2.0.224-0.xamarin.1.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 34.00 Trying other mirror.


mono-complete-6.10.0.104
#12 25.71 https://download.mono-project.com/repo/centos7-stable/m/mono-core/ibm-data-db2-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 25.71 Trying other mirror.
#12 34.87 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmonosgen-2_0-devel-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno14] HTTPS Error 504 - Gateway Timeout
#12 34.87 Trying other mirror.
#12 66.22 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-reactive-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 66.22 Trying other mirror.
#12 81.75 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-wcf-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 81.75 Trying other mirror.
#12 99.13 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-winfxcore-6.10.0.104-0.xamarin.17.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 99.13 Trying other mirror.

mono-complete-6.12.0.107
#12 27.75 https://download.mono-project.com/repo/centos7-stable/m/mono-core/libmonosgen-2_0-devel-6.12.0.107-0.xamarin.9.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 27.75 Trying other mirror.
#12 34.48 https://download.mono-project.com/repo/centos7-stable/m/mono-core/mono-reactive-6.12.0.107-0.xamarin.9.epel7.x86_64.rpm: [Errno 14] HTTPS Error 504 - Gateway Timeout
#12 34.48 Trying other mirror.
```
