### ISSUE TITLE
Mono runtime crash when using the nuget package "MailKit"

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7043]
Console application is crashing on the line,
```
var message = new MimeMessage()
```

Here is the stack trace,
```
* Assertion at method-to-ir.c:13203, condition `ins->opcode >= MONO_CEE_LAST' not metStacktrace:at  <REDACTED>
```

VSTS link https://devdiv.visualstudio.com/DevDiv/_workitems?id=564487&src=alerts&src-action=cta&fullScreen=true&tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy52c3Mtd29yay5teS13b3JraXRlbS1hc3NpZ25lZC10by1jaGFuZ2VzLXN1YnNjcmlwdGlvbiIsIlNUeXBlIjoiQ09OIiwiUmVjaXAiOjEsIl94Y2kiOnsiTklEIjoxODMwNjgxMCwiTVJlY2lwIjoibTA9MSAiLCJBY3QiOiIwODA2NGVhZS1lMjhkLTQ4YTYtOTBjNi05MjMyMDU4NjZmZjgiLCJmZiI6IkNEIn19&_a=edit

**Comment by kumpera** [comment]
I tried to reproduce it on Mac with mono 5.8 and it worked.

Could you provide information on mono version and operating system you experienced the issue?

**Comment by jstedfast** [comment]
I think this the same as https://github.com/jstedfast/MailKit/issues/617 which seems to have been resolved.

**Comment by shetty-chethan** [comment]
I'm on Mono 5.4.1.7 also using latest xamarin.mac(4.0.0.216). Creating fresh project (as mentioned here [#617](https://github.com/jstedfast/MailKit/issues/617)) didn't solve it either.

**Comment by jstedfast** [comment]
You'll need at least Mono 5.8 I think

**Comment by shetty-chethan** [comment]
Works fine on Mono 5.8.0.108.
Thanks

**Comment by marek-safar** [comment]
Seems to be resolved -> closing

**Comment by brendanzagaeski** [comment]
I'll add a little extra cross-referencing info for bookkeeping. Based on the [Xamarin Bugzilla bug](https://bugzilla.xamarin.com/show_bug.cgi?id=60625) linked in <https://github.com/jstedfast/MailKit/issues/617>, this was resolved in the mono `2017-12` branch by <https://github.com/mono/mono/pull/6242>.

**Comment by brendanzagaeski** [comment]
I'll add a little extra cross-referencing info for bookkeeping. Based on the [Xamarin Bugzilla bug](https://bugzilla.xamarin.com/show_bug.cgi?id=60625) linked in <https://github.com/jstedfast/MailKit/issues/617>, this was resolved in the mono `2017-10` branch by <https://github.com/mono/mono/pull/6020>.
